---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sarvesh-test-app-deployment"
  namespace: "default"
  labels:
    app: "sarvesh-test-app-deployment"
    owner: "sarveshwaran"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sarvesh-test-app-deployment"
      owner: "sarveshwaran"
      tier: "frontend"
  template:
    metadata:
      labels:
        app: "sarvesh-test-app-deployment"
        owner: "sarveshwaran"
        tier: "frontend"
    spec:
      containers:
      - name: "sarveshtest-demo-sha256-1"
        image: "gcr.io/searce-playground/sarveshtest-demo:latest"
        ports:
         - containerPort: 80
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sarvesh-test-app-deployment-hpa-tnca"
  namespace: "default"
  labels:
    app: "sarvesh-test-app-deployment"
    owner: "sarveshwaran"
    tier: "frontend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "sarvesh-test-app-deployment"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sarvesh-test-app-deployment
#   labels:
#     app: sarvesh-test-app
#     region: us-central1-c
#     owner: sarveshwaran 
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: sarvesh-test-app
#       tier: frontend
#   template:
#     metadata:
#       labels:
#         app: sarvesh-test-app
#         tier: frontend
#     spec:
#       containers:
#       - name: nginx
#         image: gcr.io/searce-playground/sarveshtest-demo:latest
#         ports:
#         - containerPort: 80
