apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    region: us-central1-c
    owner: sarveshwaran 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: gcr.io/searce-playground/sarveshtest-demo
        ports:
        - containerPort: 80
